# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-22 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=144, null=True)),
                ('tipo', models.CharField(max_length=144, null=True)),
                ('estado', models.CharField(max_length=144, null=True)),
                ('fecha_estimada_inicio', models.DateTimeField(null=True)),
                ('fecha_estimada_fin', models.DateTimeField(null=True)),
                ('fecha_real_inicio', models.DateTimeField(null=True)),
                ('fecha_real_fin', models.DateTimeField(null=True)),
                ('es_template', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Empresa')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.Equipo')),
            ],
        ),
    ]
