# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-22 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=144, null=True)),
                ('descripcion', models.CharField(max_length=144, null=True)),
                ('serie', models.CharField(blank=True, max_length=144, null=True)),
                ('tipo', models.CharField(blank=True, max_length=144, null=True)),
                ('estado', models.CharField(blank=True, max_length=144, null=True)),
                ('sistema', models.CharField(blank=True, max_length=144, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seguridad.Empresa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=144, null=True)),
                ('descripcion', models.CharField(max_length=144, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.Ubicacion'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.Equipo'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.Ubicacion'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together=set([('equipo', 'ubicacion')]),
        ),
    ]
