# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-06 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_auto_20161205_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectura', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Odometro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=144)),
                ('descripcion', models.CharField(max_length=144, null=True)),
                ('udm', models.CharField(choices=[('HR', 'HORAS'), ('KM', 'KILOMETROS'), ('K', 'KELVIN'), ('C', 'GRADOS CELSIUS'), ('F', 'GRADOS FAHRENHEIT')], max_length=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACT', 'ACTIVO'), ('DES', 'DESHABILITADO'), ('REP', 'EN REPARACION')], default='ACT', max_length=3),
        ),
        migrations.AddField(
            model_name='odometro',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.Equipo'),
        ),
        migrations.AddField(
            model_name='medicion',
            name='odometro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.Odometro'),
        ),
    ]
