# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-06 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_auto_20161206_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACT', 'ACTIVO'), ('DES', 'DESHABILITADO'), ('REP', 'EN REPARACION')], default='ACT', max_length=4),
        ),
    ]
